### ISSUE TITLE
Ai verificat ?

### ISSUE THREAD

**Issue by corint1** [marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh#1]
nu ma indoisc ca este functional, dar ai verificat sa fie totul corect ? si sa fie totul necesar ? am impresia ca ai copiat de undeva si intamplator s-a potrivit sa functioneze ... verifica pci-listing-ul ... 
lista de patch-uri este corecta ? ... de unde incarci atatea patch-uri cand tu ai doar doua ? ...dsdt-ul unde este ? ... dar tu il incarci ...:))))))
bafta

**Comment by marianopela** [comment]
> nu ma indoisc ca este functional, dar ai verificat sa fie totul corect ? si sa fie totul necesar ? am impresia ca ai copiat de undeva si intamplator s-a potrivit sa functioneze ... verifica pci-listing-ul ...
> lista de patch-uri este corecta ? ... de unde incarci atatea patch-uri cand tu ai doar doua ? ...dsdt-ul unde este ? ... dar tu il incarci ...:))))))
> bafta

I don’t understand a word

**Comment by marianopela** [comment]
> nu ma indoisc ca este functional, dar ai verificat sa fie totul corect ? si sa fie totul necesar ? am impresia ca ai copiat de undeva si intamplator s-a potrivit sa functioneze ... verifica pci-listing-ul ...
> lista de patch-uri este corecta ? ... de unde incarci atatea patch-uri cand tu ai doar doua ? ...dsdt-ul unde este ? ... dar tu il incarci ...:))))))
> bafta

Ok, thanks to google transate I think I got the message. It is not fully functional. Battery drains during sleep, touchpad doesn’t work and Bluetooth works badly. I still need to figure some things out. Regarding the pci devices I tried inserting the addresses manually, but it didn’t help (I know, I should clean) and I tried different patches too. Should probably clean up a bit, thanks

**Comment by corint1** [comment]
sorry for the confusion ... your name made me think you are Romanian ... in the end ... try my EFI folder ... I have 530 S ... and everything works ...

**Comment by daviddean-x** [comment]
Sure, i can help to debug, do you have Skype? Sorry I can't open new issue here, my Skype is d.faller@live.de

Bluetooth I had fixed and posted to the other GitHub repo

**Comment by daviddean-x** [comment]
@corint1 the device is a s540 and totally different one than yours

**Comment by fpx-one** [comment]
[VoodooHDA（ALC257）.kext.zip](https://github.com/marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh/files/3999333/VoodooHDA.ALC257.kext.zip)

**Comment by marianopela** [comment]
> [VoodooHDA（ALC257）.kext.zip](https://github.com/marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh/files/3999333/VoodooHDA.ALC257.kext.zip)

Always causes bootloop. Should I tweak something else?

**Comment by fpx-one** [comment]
@marianopela AppleAlc。delete

**Comment by marianopela** [comment]
> @marianopela AppleAlc。delete

I don't have it already
Note that my device has got a Conexant CX8070

**Comment by corint1** [comment]
Supported codecs AppleALC.kext
.....
Conexant | CX8070/CX11880 | layout 15
........
https://github.com/acidanthera/AppleALC/releases

**Comment by marianopela** [comment]
> Supported codecs AppleALC.kext
> .....
> Conexant | CX8070/CX11880 | layout 15
> ........
> https://github.com/acidanthera/AppleALC/releases

Already tried it. Didn’t work
Do you have

**Comment by marianopela** [comment]
> Supported codecs AppleALC.kext
> .....
> Conexant | CX8070/CX11880 | layout 15
> ........
> https://github.com/acidanthera/AppleALC/releases

Already tried it. Didn't work
Do you have the same audio codec?

**Comment by marianopela** [comment]
> Supported codecs AppleALC.kext
> .....
> Conexant | CX8070/CX11880 | layout 15
> ........
> https://github.com/acidanthera/AppleALC/releases

Already tried it. Didn't work
Do you have the same audio codec?

**Comment by corint1** [comment]
no, I didn't try, but I trust the developers ... in many other situations it worked flawlessly ... are you the first to complain ... what patches do you use? ... or ssdt? ... something is not linked ...

**Comment by marianopela** [comment]
> no, I didn't try, but I trust the developers ... in many other situations it worked flawlessly ... are you the first to complain ... what patches do you use? ... or ssdt? ... something is not linked ...

I trust them too. Even without ssdt and dsdt patching my audio wasn't working. Have you got a Conexant audio too?

**Comment by neblogas** [comment]
Hi,

I have almost the same Laptop(i7,12GB,1TB). How does the wifi card work? bluetooth? any issues? recommended buy or better DW1560?

Cheers

**Comment by corint1** [comment]
hi,
1560 or 1820a ....

**Comment by marianopela** [comment]
> Hi,
> 
> I have almost the same Laptop(i7,12GB,1TB). How does the wifi card work? bluetooth? any issues? recommended buy or better DW1560?
> 
> Cheers

After some tweaking 1820a is working just fine on my device, in 99% of the cases I’d say. DW1560 is probably better overall but it depends on your budget

**Comment by neblogas** [comment]
> > Hi,
> > I have almost the same Laptop(i7,12GB,1TB). How does the wifi card work? bluetooth? any issues? recommended buy or better DW1560?
> > Cheers
> 
> After some tweaking 1820a is working just fine on my device, in 99% of the cases I’d say. DW1560 is probably better overall but it depends on your budget

Did you buy the normal dw1820a or the Lenovo reference? Whitelist?

**Comment by daviddean-x** [comment]
It don't need to be a Lenovo branded one.

**Comment by neblogas** [comment]
You think this could work?https://www.ebay.de/itm/253397919458

It says not compatible with Lenovo.

What nvme do you have? Mine is Samsung and does not work. 
Have bought second SSD from transcend in the second m.2 slot and I could install.

Cheers

**Comment by marianopela** [comment]
> You think this could work?https://www.ebay.de/itm/253397919458
> 
> It says not compatible with Lenovo.
> 
> What nvme do you have? Mine is Samsung and does not work.
> Have bought second SSD from transcend in the second m.2 slot and I could install.
> 
> Cheers

I personally got this https://www.amazon.it/dp/B07WWT9ZHS/ref=cm_sw_r_cp_api_i_QtopEbCTA661Z
I think it’s pretty much the same, so just worry about the price

As for the SSD I didn’t change the one stock one, but I can’t recall its brand now. I think @thefiredragon is using a Samsung nvme if I recall correctly

**Comment by corint1** [comment]
https://www.tonymacx86.com/threads/install-dell-dw1820a-broadcom-bcm94350zae.265130/

For B50-70/N50-70/B40-80/B50-80/E4030/E4070/E4080/Y40-70/Y40-80/Y50-70/Y50-80/Y50-70 Touch/Y50-80 Touch
Not for other model!

**Comment by daviddean-x** [comment]
I'm using a Samsung evo Plus 970, you'll need to Upgrade the Firmware for this ssd, then the plus ones will work good with macos.

The Lenovo bios Has no white or Blacklist for m.2 ngff wifi cards. Older Lenovo has this. I also bought one on eBay

**Comment by neblogas** [comment]
@marianopela how did you get your audio to work? I have the same chipset with AppleALC.kext and layout id set to 15. internal speakers and microfone are shown. I can turn the volume, but no sound comes out. In audio midi setup app the master volume is 0 and greyed out. can not turn up.

**Comment by marianopela** [comment]
> @marianopela how did you get your audio to work? I have the same chipset with AppleALC.kext and layout id set to 15. internal speakers and microfone are shown. I can turn the volume, but no sound comes out. In audio midi setup app the master volume is 0 and greyed out. can not turn up.

You need these 
![Screenshot 2020-02-11 at 12 36 19](https://user-images.githubusercontent.com/42821024/74233541-2e796080-4ccb-11ea-814c-f99706bbbb74.png)

And this
![Screenshot 2020-02-11 at 12 37 21](https://user-images.githubusercontent.com/42821024/74233612-523ca680-4ccb-11ea-8560-f454ec7f96b6.png)
Thanks to @thefiredragon for helping

**Comment by neblogas** [comment]
@marianopela THANKS MAN!!! I have sound! Bit too low but atleast sound!
also thanks to @thefiredragon 
I also managed my card reader to work with https://github.com/syscl/Sinetek-rtsx kext. Installed in S/L/E

**Comment by neblogas** [comment]
@marianopela Trackpad patch:
https://www.notion.so/Using-VoodooI2C-on-comet-lake-cpu-e-g-i5-10210u-142930887087445eaa533120455da5dc

**Comment by marianopela** [comment]
> @marianopela Trackpad patch:
> https://www.notion.so/Using-VoodooI2C-on-comet-lake-cpu-e-g-i5-10210u-142930887087445eaa533120455da5dc

Thanks. Gonna try it now @3ig @thefiredragon
