### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by Tullaphat** [marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh#3]
Hello, I used your efi and mostly work great. except audio (no output) and brightness key is not working. can you help me fix this?

**Comment by marianopela** [comment]
Regarding audio, are you sure you have the same audio card? Mine is a Conexant cx8070, as stated in the description

To fix brightness keys you need to patch YOUR DSDT
https://www.insanelymac.com/forum/topic/305030-guide-how-to-fix-brightness-hotkeys-in-dsdt/

**Comment by Tullaphat** [comment]
On Windows my audio card show "Synaptic Audio" I'm not sure what should I do

**Comment by marianopela** [comment]
Sorry, I was busy. Did you solve?

**Comment by Tullaphat** [comment]
yes, I just try with your latest update it's solved all my problem audio and brightness key worked!!

**Comment by marianopela** [comment]
Nice
