### ISSUE TITLE
i7-10510U

### ISSUE THREAD

**Issue by mancix** [marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh#5]
Hi, I have your same model but with the i7-10510U. 
I disabled the CFG and set the boot mode to AHCI instead of RST. Are there other BIOS settings to change? 
I tried to copy your configuration with both OpenCore and Clover but with both I get a reboot during disk initialization with disk utility.

**Comment by marianopela** [comment]
Salve

Usual settings to look for are VT-d, fast and safe boot but I don’t have those in my bios 

Sorry for the delay. Did you have any luck? Have you tried changing the config a bit or looking at this? https://github.com/3ig/IdeaPad-S540-15IML-hackintosh

**Comment by mancix** [comment]
Ciao,
unfortunately I discovered that the error was due to the disk controller which is not supported by macos, the model of the SSD is the following samsung mzvlb512hbjq-000l2 and the controller is the PM891a. Right now the only solution would be to change it... Another thing that is to be fixed is the trackpad it is a different model from yours.

**Comment by marianopela** [comment]
Sorry about PM891a but you can take a look at this https://github.com/phenixcxz/xiaoXinPro13-PM981 with google translate. It seems that compatibility problem can be fixed

About trackpad it’s probably not a big deal, and it can be fixed in post installation
