### ISSUE TITLE
Please help me to fix trackpad 

### ISSUE THREAD

**Issue by mrdawn** [marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh#6]
Hello @marianopela, I have tried to fix the trackpad for the whole week, I saw that you have helped some people to solve their prolems with this laptop series, hopefully you can spend a little amount of time to help me with this problem.

This is my laptop: https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/ideapad-s-series-netbooks/s540-15iml/81ng/81ng004rvn/parts/PD500370

My APCI ID from Device Manager: \\_SB.PCI0.I2C0.TPD0

![117907002_652557688721624_7828767163918161045_n](https://user-images.githubusercontent.com/8677432/90376211-47126b00-e0a0-11ea-95b0-ed5bf2839a94.jpg)

At first, I followed the guide right [here](https://voodooi2c.github.io/) (voodoo I2C official) to patch Windows and GPI0 enable

![Screen Shot 2020-08-17 at 3 26 46 PM](https://user-images.githubusercontent.com/8677432/90374968-82139f00-e09e-11ea-86c5-ce54fbee3ae8.png)

when i open IORegExplorer and search for your ACPI ID, it does not show up although I’m pretty sure that my patch is working

![Screen Shot 2020-08-17 at 2 39 47 PM](https://user-images.githubusercontent.com/8677432/90373844-c3a34a80-e09c-11ea-861e-05323d84cc64.png)

I also tried with hot patch but it’s still being the same

![Screen Shot 2020-08-17 at 2 43 44 PM](https://user-images.githubusercontent.com/8677432/90376682-0c5d0280-e0a1-11ea-90eb-fffa791c3f4d.png)

I relized that if I install VoodooI2C and VoodooHID kext, IORegistryExplorer showed received TPD0 Device but trackpad not showing in System Preferences. GenI2C fully displayed

![Screen Shot 2020-08-17 at 2 52 04 PM](https://user-images.githubusercontent.com/8677432/90374870-5e505900-e09e-11ea-9567-794a6907bbcd.png)
![Screen Shot 2020-08-17 at 2 53 37 PM](https://user-images.githubusercontent.com/8677432/90376897-5c3bc980-e0a1-11ea-98cb-358b35fad4ce.png)
![Screen Shot 2020-08-17 at 4 00 04 PM](https://user-images.githubusercontent.com/8677432/90378799-061c5580-e0a4-11ea-9931-36a8ff1d1704.png)
![Screen Shot 2020-08-17 at 4 00 23 PM](https://user-images.githubusercontent.com/8677432/90378810-0a487300-e0a4-11ea-9df8-18f32c5449b2.png)

I have tried a lot of possible ways:

- Rebuild kextcache before restart
- Following: https://www.penghubingzhou.cn/2019/01/06/VoodooI2C%20DSDT%20Edit/
- Unlock CFG
- Change SMBIOS
- Generation DSDT from GenI2C 
- Search error in the forums and github and google
- ...
But all of it is hopeless

This is my Runme.app after install VoodooI2C.kext and VoodooHID.kext
[Send me Dawns-MacBook-Pro.zip](https://github.com/marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh/files/5083291/Send.me.Dawns-MacBook-Pro.zip)

I’m very appreciate if you can help me, have a nice day.

P/S: 
![Screen Shot 2020-08-17 at 4 16 02 PM](https://user-images.githubusercontent.com/8677432/90379821-6fe92f00-e0a5-11ea-9d12-fbb2c1bd0d33.png)

**Comment by marianopela** [comment]
Hey, did you take a look at this? You seem to have the same device https://github.com/3ig/IdeaPad-S540-15IML-hackintosh

Did you try running in polling mode? You would just need SSDT-XOSI, _OSI to XOSI rename 
I would also try removing these lines from your DSDT (don't load SSDT_GPI0)
![Screenshot 2020-08-18 at 10 34 18](https://user-images.githubusercontent.com/42821024/90490008-62cc4e80-e13e-11ea-8ce0-94f7e862c348.png)

**Comment by mrdawn** [comment]
To get into the polling mode, i need to unpin GPI0, but my laptop automatically pin GPI0, i just need patch XOSI but no need GPI0 and my laptop has still taken the kext.

I found the similar problem at: https://github.com/3ig/IdeaPad-S540-15IML-hackintosh/issues/1

![Screen Shot 2020-08-19 at 12 52 50 PM](https://user-images.githubusercontent.com/8677432/90597304-01c67880-e21b-11ea-9fc4-d2605e10cae1.png)

**Comment by ghost** [comment]
If you solved the problem, can you post your file? We are using the same ID.
